/* RECIPE ACTION TYPES */
export const ADD_RECIPE = 'ADD_RECIPE'
export const FETCH_RECIPE = 'FETCH_RECIPE'
export const SET_RECIPES = 'SET_RECIPES'

/* INGREDIENT ACTION TYPES */
export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const SET_INGREDIENT = 'SET_INGREDIENT'